#!/bin/bash

DUMP=0;
if [ "$1" == "--dump" ]; then
    shift;
    DUMP=1;
fi;

ID=$1;
i=0;
shift;

for el in $(curl -sL "https://www.youtube.com/playlist?list=${ID}" | perl -ne '$enabled = true if m{browse-items-primary}; $enabled = false if m{footer-container}; print if $enabled;' | grep -o '/watch?v=[^ &]\+&' | uniq);
do
    i=$((i+1));
    if [ "$DUMP" -eq "0" ]; then
        echo "Playing [$i] http://youtube.com${el}";
        youtube "youtube.com${el}" $* || break;
    else
        echo "http://youtube.com${el}";
    fi;
done;
