#!/bin/bash

ID=$1;
shift;

for el in $(curl -sL "http://www.youtube.com/playlist?list=${ID}&feature=plcp" | perl -ne '$enabled = true if m{"playlist-video-item}; $enabled = false if m{"playlist-pager"}; print if $enabled;' | grep -o '/watch?v=[^ &]\+&' | uniq);
do
    echo "Playing http://youtube.com${el}";
    youtube "youtube.com${el}" $* || break;
done;
